DeCA_configs = {
 ('GMF', "ml100k"): {'iterative': True,
   'C_2': 1000,
   'C_1': 1000,
   'epochs': 50,
   'early_stop': False,
   'lambda0': 0.1,
   'alpha': 1},
 ('NeuMF', "ml100k"): {'iterative': True,
   'C_2': 10,
   'C_1': 1000,
   'epochs': 50,
   'early_stop': False,
   'lambda0': 0.01,
   'alpha': 1},
 ('CDAE', "ml100k"): {'iterative': True,
   'C_2': 100,
   'C_1': 1000,
   'epochs': 500,
   'early_stop': False,
   'lambda0': 1.0,
   'alpha': 0.5},
 ('LightGCN', "ml100k"): {'iterative': True,
   'C_2': 100,
   'C_1': 100,
   'epochs': 300,
   'early_stop': False,
   'lambda0': 0.1,
   'alpha': 0.0},
 ('GMF', 'adressa'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 0.0,
  'alpha': 1},
 ('NeuMF', 'adressa'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 1,
  'alpha': 0},
 ('CDAE', 'adressa'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 500,
  'early_stop': False,
  'lambda0': 0,
  'alpha': 0},
 ('LightGCN', 'adressa'): {'iterative': True,
  'C_2': 1000,
  'C_1': 10,
  'epochs': 300,
  'early_stop': False,
  'lambda0': 10,
  'alpha': 0},
 ('GMF', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 0.01,
  'alpha': 1},
 ('NeuMF', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 1000,
  'alpha': 0.5},
 ('CDAE', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 15,
  'early_stop': False,
  'lambda0': 0.1,
  'alpha': 0},
 ('LightGCN', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 300,
  'early_stop': False,
  'lambda0': 0.01,
  'alpha': 1}}

DeCAp_configs = {
 ('GMF', "ml100k"): {'iterative': True,
   'C_2': 1000,
   'C_1': 1000,
   'epochs': 50,
   'early_stop': False,
   'lambda0': 0.1,
   'alpha': 1},
 ('NeuMF', "ml100k"): {'iterative': True,
   'C_2': 10,
   'C_1': 100,
   'epochs': 50,
   'early_stop': False,
   'lambda0': 0.0,
   'alpha': 1},
 ('CDAE', 'ml100k'): {'iterative': True,
   'C_2': 10,
   'C_1': 1000,
   'epochs': 500,
   'early_stop': False,
   'lambda0': 1,
   'alpha': 1},
 ('LightGCN', "ml100k"): {'iterative': True,
   'C_2': 1,
   'C_1': 1,
   'epochs': 300,
   'early_stop': False,
   'lambda0': 0.0,
   'alpha': 1.0},
 ('GMF', 'adressa'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 0.01,
  'alpha': 1},
 ('NeuMF', 'adressa'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 1,
  'alpha': 1},
 ('CDAE', 'adressa'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 500,
  'early_stop': False,
  'lambda0': 0,
  'alpha': 1},
 ('LightGCN', 'adressa'): {'iterative': False,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 300,
  'early_stop': False,
  'lambda0': 0.01,
  'alpha': 0.5},
 ('GMF', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 0.01,
  'alpha': 1},
 ('NeuMF', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 50,
  'early_stop': False,
  'lambda0': 1000,
  'alpha': 0},
 ('CDAE', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 100,
  'epochs': 500,
  'early_stop': False,
  'lambda0': 0.1,
  'alpha': 0},
 ('LightGCN', 'yelp'): {'iterative': True,
  'C_2': 10,
  'C_1': 1000,
  'epochs': 300,
  'early_stop': False,
  'lambda0': 0.01,
  'alpha': 1}}


baseline_configs = {
 ('GMF', 'ml100k'): {'epochs': 20, 'early_stop': True},
 ('NeuMF', 'ml100k'): {'epochs': 100, 'early_stop': True},
 ('CDAE', 'ml100k'): {'epochs': 200, 'early_stop': False},
 ("LightGCN", 'ml100k'): {'epochs': 200, 'early_stop': True},
 ('GMF', 'modcloth'): {'epochs': 40, 'early_stop': True},
 ('NeuMF', 'modcloth'): {'epochs': 40, 'early_stop': True},
 ('CDAE', 'modcloth'): {'epochs': 40, 'early_stop': False},
 ('LightGCN', 'modcloth'): {'epochs': 40, 'early_stop': False},
 ('GMF', 'adressa'): {'epochs': 10, 'early_stop': True},
 ('NeuMF', 'adressa'): {'epochs': 10, 'early_stop': True},
 ('CDAE', 'adressa'): {'epochs': 50, 'early_stop': True},
 ('LightGCN', 'adressa'): {'epochs': 15, 'early_stop': False},
 ('GMF', 'yelp'): {'epochs': 10, 'early_stop': True},
 ('NeuMF', 'yelp'): {'epochs': 10, 'early_stop': False},
 ('CDAE', 'yelp'): {'epochs': 15, 'early_stop': False},
 ('LightGCN', 'yelp'): {'epochs': 10, 'early_stop': False}}


lambdas = {
 ('GMF', 'ml100k', 'normal'): 0.1,
 ('NeuMF', 'ml100k', 'normal'): 0.01,
 ('CDAE', 'ml100k', 'normal'): 1.0,
 ('LightGCN', 'ml100k', 'normal'): 0.01,
 ('GMF', 'modcloth', 'normal'): 0.1,
 ('NeuMF', 'modcloth', 'normal'): 10,
 ('CDAE', 'modcloth', 'normal'): 1,
 ('LightGCN', 'modcloth', 'normal'): 0.1,
 ("GMF", 'adressa', 'normal'): 0.01,
 ("NeuMF", 'adressa', 'normal'): 1,
 ('CDAE', 'adressa', 'normal'): 1,
 ('LightGCN', 'adressa', 'normal'): 0.01,
 ('NeuMF', 'yelp', 'normal'): 100,
 ('GMF', 'yelp', 'normal'): 0.01,
 ('CDAE', 'yelp', 'normal'): 0.1,
 ('LightGCN', 'yelp', 'normal'): 0.01,
}


def get_config(model, dataset, method):
 if method == 'DeCA':
  param = DeCA_configs[(model, dataset)]
 elif method == 'DeCAp':
  param = DeCAp_configs[(model, dataset)]
 else:
  param = baseline_configs[(model, dataset)]
  param['lambda0'] = lambdas[(model, dataset, 'normal')]
 return param
