# training parameters
lr: 0.001
batch_size: 1024
top_k: [5, 10, 20, 50, 100]
test_batch_size: 256


# model parameters
dropout: 0.0
factor_num: 32
num_layers: 3
num_ng: 1
dropout: 0.0


# DCF Denoising parameters
relabel_ratio: 0
co_lambda: 0.0001
time_step: 1
num_gradual: 3500
drop_rate: 0.2
exponent: 1


# 其他参数
