# training parameters
lr: 0.001
batch_size: 1024
top_k: [5, 10, 20, 50, 100]
test_batch_size: 256


# model parameters
dropout: 0.0
factor_num: 32
num_layers: 3
num_ng: 1
dropout: 0.0

# RCE Denoising parameters
RCE_alpha: 0.25
# TCE Denoising parameters
drop_rate: 0.2
num_gradual: 30000


# 其他参数
